swagger: "2.0"
info:
  version: 1.0.0
  title: "genetraps"
  description: Api for genetraps-opensource
  contact:
    name: intelliseq sp. z o.o.
    email: contact@intelliseq.pl
    url: http://intelliseq.pl/
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /hello:
    get:
      description: The basic hook to check if server is alive
      responses:
        200:
          description: Response "ok" whes server is up
          schema: 
            $ref: '#/definitions/Status'
  /touch:
    get:
      description: touch
      responses:
        200:
          description: desc
  /mkdir:
    get:
      description: Creates directory and returns it's name
      responses:
        200:
          description: The name of the directory
          schema: 
            $ref: '#/definitions/Mkdir'
definitions:
  Status:
    properties:
      status: 
        type: string
  Mkdir:
    properties:
      response:
        type: integer
        format: int64