version: '2'
services:
  client-dx:
    image: 958510462668.dkr.ecr.us-east-1.amazonaws.com/genetraps-client-dx:0e678ad5797455a6b2f24c438d427596
    ports:
      - "8085:8085"
    logging:
      driver: awslogs
      options:
        awslogs-group: genetraps-logs
        awslogs-region: us-east-1
        awslogs-stream-prefix: api-security-log
