#!/bin/bash
# iseq-fastqc 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {

    echo "Value of fastq_file: '$fastq_file'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    dx download "$fastq_file" -o fastq_file.fq.gz

    mkdir /tmp/fastqc
    fastqc fastq_file.fq.gz --outdir="/tmp/fastqc/"
    cp /tmp/fastqc/*.html summary_html
    unzip -p /tmp/fastqc/*.zip */fastqc_data.txt > summary_txt
    summary_html=$(dx upload summary_html --brief)
    summary_txt=$(dx upload summary_txt --brief)

    # The following line(s) use the utility dx-jobutil-add-output to format and
    # add output variables to your job's output as appropriate for the output
    # class.  Run "dx-jobutil-add-output -h" for more information on what it
    # does.

    dx-jobutil-add-output summary_html "$summary_html" --class=file
    dx-jobutil-add-output summary_txt "$summary_txt" --class=file
}
